pico_controller:
  ros__parameters:
    pitch_pid:
      Kd: 401
      Ki: 0
      Kp: 301
    roll_pid:
      Kd: 401
      Ki: 0
      Kp: 301
    throttle_pid:
      Kd: 401
      Ki: 0
      Kp: 301
